In [1]:
import math
import numpy as np

In [2]:
import os
import numpy as np
import torch
from sklearn.preprocessing import scale
from torch.utils.data import Dataset, DataLoader
import shutil

In [5]:
root_dir = "../../data/iq"


In [7]:
data = np.load(os.path.join(root_dir, "iq_train_data.npy"))
label = np.load(os.path.join(root_dir, "iq_train_label.npy"))
data.shape

(5589, 32, 1600, 2)

In [16]:
# label = label.reshape(-1, 1000)
# label = np.argmax(label, axis=1)
# label
idx = 48423
a = data[idx // data.shape[1]][idx % data.shape[1]]


(1600, 2)

In [23]:
a[-160:,:]

array([[ 0.21716668, -0.26015897],
       [ 0.21323899, -0.25951445],
       [ 0.20949198, -0.25895386],
       [ 0.20588322, -0.25847356],
       [ 0.20243426, -0.25810919],
       [ 0.19913313, -0.25780901],
       [ 0.19594677, -0.25764349],
       [ 0.19296249, -0.25759132],
       [ 0.19012221, -0.25762805],
       [ 0.18747757, -0.25777659],
       [ 0.18498969, -0.25805752],
       [ 0.1826727 , -0.25842575],
       [ 0.1805464 , -0.25897095],
       [ 0.17855039, -0.25969295],
       [ 0.17678322, -0.26050143],
       [ 0.1752406 , -0.26147027],
       [ 0.17381999, -0.26251165],
       [ 0.17256008, -0.26365286],
       [ 0.1715281 , -0.26494948],
       [ 0.17068289, -0.26633604],
       [ 0.17007331, -0.26780413],
       [ 0.16960399, -0.2694165 ],
       [ 0.16936944, -0.27117526],
       [ 0.1693842 , -0.27303924],
       [ 0.16960454, -0.27507328],
       [ 0.17004199, -0.27727985],
       [ 0.17069014, -0.27963021],
       [ 0.17153534, -0.28212768],
       [ 0.17263212,

In [7]:
label.shape

(44448,)

In [150]:
a = real[0]
a

array([[-1.41196319, -1.41265668, -1.41966455, ..., -1.37116466,
        -1.37177234, -1.37627449],
       [-1.38312791, -1.38904633, -1.39165043, ..., -1.43330288,
        -1.42688303, -1.43168191],
       [-1.44733671, -1.47038196, -1.49681334, ..., -1.46117692,
        -1.43617308, -1.41466257],
       ...,
       [-0.53874243, -0.467287  , -0.39994501, ..., -0.77777127,
        -0.73495998, -0.65274164],
       [-0.55084288, -0.44737176, -0.3547422 , ..., -0.71042355,
        -0.73206296, -0.70425251],
       [-0.63588413, -0.54488798, -0.45143569, ..., -0.59128294,
        -0.56920226, -0.51096973]])

In [151]:
b = imag[0]
b

array([[-1.7088408 , -1.77526306, -1.84101529, ..., -2.17547156,
        -2.31239829, -2.5024347 ],
       [-2.74280895, -3.02991872,  2.9324327 , ..., -0.8267879 ,
        -0.91648389, -1.05491368],
       [-1.23585279, -1.46696851, -1.77322546, ..., -2.23637879,
        -2.33042061, -2.42719004],
       ...,
       [ 0.24291371,  0.26144914,  0.26100079, ...,  1.41028911,
         0.97746998,  0.58556475],
       [ 0.23840409, -0.07365156, -0.36105309, ..., -0.19709133,
        -0.07632666,  0.04413309],
       [ 0.13446415,  0.18252829,  0.19238191, ...,  1.43171813,
         1.02521901,  0.63421204]])

In [156]:
np.concatenate((a, b), axis = 1).shape

(20, 160)

In [147]:
label.shape

(178848, 1000)

IndexError: invalid index to scalar variable.

NameError: name 'b' is not defined

(1.0, 1.5707963267948966)

In [13]:
data

array([[[[-6.94761317e-03, -5.00087017e-02],
         [-1.02145847e-02, -4.92590674e-02],
         [-1.29380905e-02, -4.67089395e-02],
         ...,
         [ 3.68595717e-02,  2.63316683e-01],
         [ 1.40977554e-01,  2.32239017e-01],
         [ 2.31159793e-01,  1.70037870e-01]],

        [[-4.07877859e-01, -2.70551381e-01],
         [-4.69729709e-01,  1.68792543e-01],
         [-1.39194888e-01,  4.67156264e-01],
         ...,
         [ 5.76811492e-02,  3.72623263e-01],
         [ 2.90586409e-01,  1.50457347e-01],
         [ 2.31532611e-01, -1.23711850e-01]],

        [[ 1.51814685e-01, -1.11622818e-01],
         [ 1.56215509e-01, -1.10753147e-01],
         [ 1.60630515e-01, -1.09811216e-01],
         ...,
         [-8.94240242e-02, -6.34347700e-02],
         [-9.07070665e-02, -6.39418784e-02],
         [-9.20584328e-02, -6.45844608e-02]],

        ...,

        [[-7.51024785e-02,  1.82505362e-02],
         [-1.04344181e-01,  2.50806316e-02],
         [-1.32248155e-01,  3.83975593

In [22]:
data1 = data.transpose(0, 1, 3, 2)
data1

array([[[[-6.94761317e-03, -1.02145847e-02, -1.29380905e-02, ...,
           3.68595717e-02,  1.40977554e-01,  2.31159793e-01],
         [-5.00087017e-02, -4.92590674e-02, -4.67089395e-02, ...,
           2.63316683e-01,  2.32239017e-01,  1.70037870e-01]],

        [[-4.07877859e-01, -4.69729709e-01, -1.39194888e-01, ...,
           5.76811492e-02,  2.90586409e-01,  2.31532611e-01],
         [-2.70551381e-01,  1.68792543e-01,  4.67156264e-01, ...,
           3.72623263e-01,  1.50457347e-01, -1.23711850e-01]],

        [[ 1.51814685e-01,  1.56215509e-01,  1.60630515e-01, ...,
          -8.94240242e-02, -9.07070665e-02, -9.20584328e-02],
         [-1.11622818e-01, -1.10753147e-01, -1.09811216e-01, ...,
          -6.34347700e-02, -6.39418784e-02, -6.45844608e-02]],

        ...,

        [[-7.51024785e-02, -1.04344181e-01, -1.32248155e-01, ...,
          -3.04771443e-01, -2.62068588e-01, -2.24777408e-01],
         [ 1.82505362e-02,  2.50806316e-02,  3.83975593e-02, ...,
           3.99791

In [23]:
data1 = data1.reshape(data1.shape[0] * data1.shape[1], data1.shape[2] * data1.shape[3])

array([[-0.00694761, -0.01021458, -0.01293809, ...,  0.26331668,
         0.23223902,  0.17003787],
       [-0.40787786, -0.46972971, -0.13919489, ...,  0.37262326,
         0.15045735, -0.12371185],
       [ 0.15181468,  0.15621551,  0.16063051, ..., -0.06343477,
        -0.06394188, -0.06458446],
       ...,
       [-0.20759182, -0.15384529, -0.10030015, ..., -0.13037296,
        -0.20214288, -0.23993298],
       [-0.05676183, -0.05086403, -0.04434363, ...,  0.0528048 ,
        -0.07458325, -0.19553563],
       [-0.57249077, -0.53091036, -0.44983612, ..., -0.77007387,
        -0.63568325, -0.46482703]])

In [12]:
data1.s

(5589, 32, 2, 1600)

In [56]:
data1[:][:][:][0].shape

(32, 2, 1600)

In [23]:
a

array([[-0.00694761, -0.0500087 ],
       [-0.01021458, -0.04925907],
       [-0.01293809, -0.04670894],
       ...,
       [ 0.03685957,  0.26331668],
       [ 0.14097755,  0.23223902],
       [ 0.23115979,  0.17003787]])

In [21]:
b

array([-0.01021458, -0.04925907])